name: Latest blog post workflow
on:
  schedule:
    # 每天 UTC 0 点运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://blog.yokumi.cn/atom.xml'
